meta_product_name: "Go Girl"
meta_title: "Go Girl | Get home safe"
meta_description: "Walking shouldn't be scary. We'll tell you how to get to wherever you want to go - and which areas to avoid on your way"
meta_image: "splash_page.png" # should exist in `app/assets/images/`
